# Generated by Django 5.1.2 on 2024-10-28 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_category_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
