# Generated by Django 5.1.2 on 2024-11-27 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_order_date_orderd_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='date_orderd',
            new_name='date_ordered',
        ),
    ]
