# Generated by Django 5.1.2 on 2024-11-27 10:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_rename_date_orderd_order_date_ordered'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_ordered',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2024, 11, 27, 12, 39, 8, 768683)),
        ),
    ]
